### ISSUE TITLE
OK, but...

### ISSUE THREAD

**Issue by okonomiyaki3000** [selfagency/microsoft-drop-ice#110]
Sorry if I'm raining on your parade but remember a week or two ago when everybody was like "If MS buys GH, I'm going back to SourceForge" or whatever? I think everybody knows these are hollow threats. Good luck though.

**Comment by selfagency** [comment]
[You're wrong](https://www.bleepingcomputer.com/news/technology/gitlab-sees-huge-traffic-spike-after-news-of-microsoft-buying-github/) but thanks for your input.
