### ISSUE TITLE
Visiting a detention centre

### ISSUE THREAD

**Issue by jerriep** [selfagency/microsoft-drop-ice#111]
I am curious about how many of the people signing here have ever actually visited a detention centre to give those people some company, or did anything else to *directly* better these people's immediate dire situation?

I don't know about the US, but I have visited the detention centre here in Bangkok, and I can tell you that the people appreciate visitors. They appreciate someone from the outside to talk to. They appreciate that it gives them the opportunity to get out of their cramped quarters for a while. They appreciate the food and other gifts that the visitors bring them.

So maybe, instead of signing petitions and trying to bully companies into doing certain things, why not take some initiative yourselves, do a trip to one of these centres and go make someone's day a little better.

BTW, governments across the world are involved daily in causing a lot of pain and suffering in many people's lives. If you want to be consistent you should start boycotting any company that does any sort of business with any government.

**Comment by jerriep** [comment]
BTW, on the off chance that some of you may take this to heart, you typically cannot just randomly pitch up at a detention centre. You need to visit a specific person and you will require their detainee number (or something similar).

So this will require some actual effort on your side. Best is to work through an organization (typically religious organizations) who visits detainees. They will be able to assist you.

**Comment by selfagency** [comment]
They won't even let U.S. Congresspeople and Senators into the centers to view the conditions let alone volunteers. I read earlier about a doctor who contacted ICE and offered to volunteer and they turned her away.

**Comment by jerriep** [comment]
If I just pitch up randomly at a detention centre here in Thailand, they would also not allow me in. You need to go during visiting hours. And you need the name and detention number of the person you are visiting.

Here is a list of all the detention centres from the ICE website:
https://www.ice.gov/detention-facilities

I did a quick spot check and each one I checked had visiting hours listed as well as information on sending items to detainees.

I would suggest you do not take everything you read at face value. The media does not have your interest at heart, nor does it have the interest of the detainees at heart. The media is there to create fear, confusion and sensation. 

Maybe there are certain centres you cannot visit, but there are many that you **can** visit. And there are many detainees whose lives you **can** make better with that visit. It may not be one of the detainees from the groups the media is making a fuss about right now, but it is still a human being who will appreciate some unconditional love and kindness from a fellow human being.

It won't be easy. It will require a genuine effort on your side. But it will make a **real** difference. Please try.

**Comment by fcastilloec** [comment]
@jerriep I love the intention behind your post. I would just change one thing from your original post:

> So maybe, instead of signing petitions and trying to bully companies into doing certain things, why not take some initiative yourselves, do a trip to one of these centres and go make someone's day a little better.

"So maybe, **in addition to** signing petitions to prevent companies from doing business with ICE, why not take some initiative yourselves...."

There's nothing wrong, actually the contrary, with signing the petition here. What's wrong is people thinking that by signing this petition is enough.
It's a wonderful suggestion you gave on how people can also help more directly on top of signing this petition.

**Comment by jerriep** [comment]
@fcastilloec  I do however not agree with the tactics being used (blackmail and manipulation) and I am not sure everyone has really thought this through.

Let's assume for a moment that GitHub/Microsoft ignores this and everyone moves to GitLab. How long do you think it will take me to find a customer of GitLab which also engages in some sort of morally reprehensible behaviour? I am willing to bet I won't have to look very far.

What is everyone going to do then? Blackmail and bully GitLab as well? And where to then?

Also, right now the US armed forces are busy dropping bombs somewhere in the Middle East (and they have been doing so for decades). They have destroyed the homes and lives of millions - either through their direct actions or through their funding or rebel groups (a.k.a. terrorists). If you want to be consistent about the enforcing the values described in this repo, then you damn well better stop doing business with any company remotely involved with the US armed forces - or for that matter with any government on this planet.

Another example: There have been numerous reports about Amazon's horrible treatment of workers in their distribution centres. If you're going to be consistent about enforcing "general human kindness" then you better stop doing business with Amazon as well. Better go find another hosting provider, my friends.

Look, I cannot tell you what to do. It is still thankfully - for the most part - a free world. Just know that you are helping to shape the world of tomorrow with your actions today. And if one day, say 20 years from now, you wake up in a world where no-one can have a proper discussion about differences and the world is filled with intolerance against anyone who thinks or acts differently, then you better go have a look in the mirror and ask yourself what part you played in helping to shape that world.

**Comment by jerriep** [comment]
Case in point re. GitLab:

![image](https://user-images.githubusercontent.com/1006420/41770541-bc17d974-763c-11e8-85e3-e3519a0dadc8.png)

Not sure GitLab is the correct option... unless you think the US Air Force dropping bombs on innocent people halfway across the globe is acceptable?

**Comment by KokeCacao** [comment]
According to these posts, the most 'correct' thing to do is to leave US unless you think that supporting many U.S. organizations (like U.S. Air Force and ICE) using your tax is acceptable. （╯#-皿-)╯~~╧═╧

**Comment by selfagency** [comment]
@jerriep With your remarks about blackmail and bullying and "intolerance against anyone who thinks or acts differently," you made it clear that you are not here for the benefit of refugees, asylum seekers, and undocumented immigrants, but as a concern troll. As such, I am closing this ticket.
