### ISSUE TITLE
Y'all should move to gitlab anyway

### ISSUE THREAD

**Issue by Keziolio** [selfagency/microsoft-drop-ice#171]

**Comment by sovietspaceship** [comment]
why are you still here then

**Comment by selfagency** [comment]
Thanks for your input.

**Comment by checkraiser** [comment]
Then if MS buy gitlab in future, what to do ?

**Comment by Keziolio** [comment]
self host gitlab since it's free software

**Comment by sovietspaceship** [comment]
what if they make it proprietary

**Comment by selfagency** [comment]
there are a dozen different options for self-hosting git repos and a dozen different options for hosted git repos.

**Comment by truongnmt** [comment]
But what make Github most is its community tho

**Comment by cfanoulis** [comment]
Imho The line of priority in hosted git is:
~~Github~~=>Gitlab=>~~Zuck~~Bitbucket=>Uploading .zip archives of code on Mediafire
