### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by vsbatista** [selfagency/microsoft-drop-ice#209]
Hi,
If im not mistaken, there was a repo a few weeks ago with the same kind of political engagement. They were banned from trending repos. The reason? The violated the TOS by not publishing anything related to code or something like that(honestly, I never read the TOS). I’ll not judge them or you, but I think they can make the same with you guys. Watch out!
BTW, this subject is a great one to discuss on a “neutral” place, like reddit or hn.

**Comment by selfagency** [comment]
Not too worried about it, but thanks for the heads up. And yeah, there's a discussion on [HN](https://news.ycombinator.com/item?id=17369690) and far less civil discussion on various threads on Reddit along the lines of "Fuck SJWs!" etc. which I won't bother linking to.
