### ISSUE TITLE
I'm volunteering to help with this repository

### ISSUE THREAD

**Issue by randolf** [selfagency/microsoft-drop-ice#235]
To the organizers of this repository, I'm volunteering to help with reviewing and approving PRs, with the hope of reducing your time requirements.

I really like this project, and I think it's an innovating and very interesting way to use GitHub.

**Comment by selfagency** [comment]
Thanks Randolf. Your PR reviews have been helpful. Keep 'em coming.

**Comment by randolf** [comment]
Okay, thank you.  I'll continue with that then.
(I was away from the internet for quite a few days because Windows 10 on my laptop crashed itself beyond repair, and so I switched to Linux, which is more than twice as fast, and I'm mostly up-to-speed now.)
