### ISSUE TITLE
direct action through github against ICE

### ISSUE THREAD

**Issue by PaulFree14** [selfagency/microsoft-drop-ice#298]
Happy to discover this respiratory.

I just like to share some thoughts to expand the idea of leaving github. 

I've been discussing with a couple of devs. Many felt that they won't dedicate for the moment resources to organize the drop out of github. 

So I believe an action where also those that don't want to leave in that moment can participate in, can expand our reach and strengh.

Here some thoughts:

- setting a date to strike
- using github during the strike to spread and collect info about ICE and microsoft involvment, and how it is linked to ones own usage of github
- calling within the strike for a date we will drop out, in case doesn't change their position
- using the strike to deconstruct fascist/racist ideology 
- call onto others to reflect their privilidges
...
basicly, stop coding for some days for a politizising process within github

 Here's one of the threads I've discussed with devs:
(it's a long one...)
https://github.com/TwidereProject/Twidere-Android/issues/1135

**Comment by jamiebuilds** [comment]
There's already an issue about setting up a date to leave #237

**Comment by PaulFree14** [comment]
@jamiebuilds
yes I know. Looks as there is some miss-understanding.

In this issue I tried to give a reasoning why it could be usefull to expand from the idea of 'just' leaving, and giving some idea what it could be.

So as the title says: 'direct action through github against ICE'
Can be a strike for some days, can be an entire boycott, can be using our repositories to create within a strike a discource on how to resist ICE...
