### ISSUE TITLE
Have a text outlining a migration process for participants

### ISSUE THREAD

**Issue by ctrlplusb** [selfagency/microsoft-drop-ice#30]
Great initiative all.

It would be great if there was a guide (or a link to one), showing the alternatives to GitHub, along with a migration process - in the event that Microsoft stands their ground.

Perhaps outlining how easy it would be to move away from GitHub may draw further participants?

❤️

**Comment by alichtman** [comment]
https://docs.gitlab.com/ee/user/project/import/github.html

Drop this link on the page somewhere.

**Comment by selfagency** [comment]
added a link to the words "leave the site" in the petition text

**Comment by JohnMH** [comment]
The wording of this is slightly triggering, could it be renamed to something maybe a bit less aggressive? I'm thinking "Have text outlining a process for leaving GitHub"
