### ISSUE TITLE
Nobody will miss you soy drinkers

### ISSUE THREAD

**Issue by woohooatb** [selfagency/microsoft-drop-ice#343]
What have you contributed to Microsoft? Writing a communist manifesto? lmao

What else after this? Ford employees walking out because cops use their cars to catch criminals?

**Comment by kidmillions** [comment]
Whether or not this organizing effort succeeds, you are definitely showing your asses by gloating in a github issues section.

Thank you for your implicit support for ICE.

**Comment by randolf** [comment]
@woohooatb The bigger picture here is that children have been separated from their families at the borders, which is widely regarded as an entirely unacceptable violation of their human rights.

**Comment by teran-mckinney** [comment]
I agree that it's unfortunate some children are separated from their families at the border. However, this happens only for illegal crossings which are already dangerous for the parents and children. And generally speaking in the States if the parents commit a crime, they get separated when the parents go to jail. I don't hear complaints about that.

This isn't really a human rights violation to me. They chose to break the law of a nation that they are not citizens of, and these are some of the consequences.

**Comment by selfagency** [comment]
this dork seriously opened a github account just to talk trash to us
