### ISSUE TITLE
Important information 

### ISSUE THREAD

**Issue by SRGOM** [selfagency/microsoft-drop-ice#389]
Psa: cages were built by Obama. He also had 7-country travel ban, all Muslim. He also killed a US citizen without trial. He deported more illegal s than Trump.  

Ask Microsoft to drop dnc as well.

**Comment by thejoaov** [comment]
I didn't get your point... if we didn't this before, it means that we can never ever do something like this? If it was obama, bush, whatever... It needs to stop now.

**Comment by selfagency** [comment]
imagine thinking i didn't also oppose obama's deportation machine
