### ISSUE TITLE
Potential for merge conflicts

### ISSUE THREAD

**Issue by emhoracek** [selfagency/microsoft-drop-ice#4]
NeverAgain.tech used Github for a petition and we spent many hours resolving literally hundreds of conflicts. Consider using a Jekyll collection instead: 
https://github.com/neveragaindottech/neveragaindottech.github.io/pull/472

I would be happy to set it up for you if you'd like to try it!

**Comment by selfagency** [comment]
That would be wonderful. Thank you!

**Comment by selfagency** [comment]
closing to focus on #22
