### ISSUE TITLE
Do you need help merging PR's?

### ISSUE THREAD

**Issue by HelenGezahegn** [selfagency/microsoft-drop-ice#406]
If given access, I can help merge the PR's coming in. 😄

**Comment by HelenGezahegn** [comment]
@selfagency

**Comment by randolf** [comment]
> If given access, I can help merge the PR's coming in.

I've also offered to help with this.  It would be great to work as a team.

**Comment by selfagency** [comment]
Added you both as collaborators on the repo. I moved all my stuff off of here a while ago, so I don't really check in very often. Sorry for that.

**Comment by HelenGezahegn** [comment]
No worries @selfagency. Thanks for adding us!
